//@version=5
indicator("BBSR Extreme Tablo ile Beraber", overlay=true, shorttitle="BBSR Extreme Tablo ile Beraber")

// General Inputs
src = input(close, title="Source")
offset = input.int(0, title="Offset", minval=-500, maxval=500)

// Bollinger Inputs
length = input.int(10, title="Bollinger Band Length", minval=1)
mult = input.float(2.0, title="StdDev", minval=0.001, maxval=50)

// Bollinger Code
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev

// Stoch Inputs
smoothK = input.int(3, "K", minval=1)
smoothD = input.int(3, "D", minval=1)
lengthRSI = input.int(9, "RSI Length", minval=1)
lengthStoch = input.int(9, "Stochastic Length", minval=1)

upperlimit = input.float(92, "Upper Limit", minval=0.01)
lowerlimit = input.float(8, "Lower Limit", minval=0.01)

// Stochastic Code
rsi1 = ta.rsi(src, lengthRSI)
k = ta.sma(ta.stoch(rsi1, rsi1, rsi1, lengthStoch), smoothK)
d = ta.sma(k, smoothD)

// Evaluation
Bear = close[1] > upper[1] and close < upper
     and k[1] > upperlimit and d[1] > upperlimit
Bull = close[1] < lower[1] and close > lower
     and k[1] < lowerlimit and d[1] < lowerlimit

// Plots
plotshape(Bear, style=shape.triangledown, location=location.abovebar, color=color.new(color.red, 0), size=size.tiny)
plotshape(Bull, style=shape.triangleup, location=location.belowbar, color=color.new(color.green, 0), size=size.tiny)

// Table Integration
var tableColor = input.color(title="Table Color: ", defval=color.rgb(0, 175, 200, 20))
var tableTextHeaderColor = input.color(title="Text Color: ", defval=color.rgb(255, 255, 0, 0))
var tableBGColor = input.color(title="Background Color: ", defval=color.rgb(0, 255, 0, 90))

var string[] signalArr = array.new_string(0)

showFunc() =>
    ((Bear or Bull) and (bar_index == bar_index[0]))

// Son barı kontrol etme ve tabloya ekleme
sb1 = request.security('BINANCE:BTCUSDT', timeframe.period, showFunc())
sb2 = request.security('BINANCE:SOLUSDT', timeframe.period, showFunc())
sb3 = request.security('BINANCE:AVAXUSDT', timeframe.period, showFunc())
sb4 = request.security('BINANCE:ETCUSDT', timeframe.period, showFunc())
sb5 = request.security('BINANCE:MAVUSDT', timeframe.period, showFunc())
sb6 = request.security('BINANCE:RVNUSDT', timeframe.period, showFunc())
sb7 = request.security('BINANCE:HOOKUSDT', timeframe.period, showFunc())
sb8 = request.security('BINANCE:DYDXUSDT', timeframe.period, showFunc())
sb9 = request.security('BINANCE:NTRNUSDT', timeframe.period, showFunc())
sb10 = request.security('MEXC:GTCUSDT', timeframe.period, showFunc())
sb11 = request.security('MEXC:RDNTUSDT', timeframe.period, showFunc())
sb12 = request.security('OKX:DGBUSDT', timeframe.period, showFunc())
sb13 = request.security('CRYPTO:CELOUSD', timeframe.period, showFunc())
sb14 = request.security('CRYPTO:PEPEUSD', timeframe.period, showFunc())
sb15 = request.security('GATEIO:MDTUSDT', timeframe.period, showFunc())
sb16 = request.security('MEXC:BLURUSDT', timeframe.period, showFunc())
sb17 = request.security('GATEIO:FLOKIUSDT', timeframe.period, showFunc())
sb18 = request.security('GATEIO:ENSUSDT', timeframe.period, showFunc())
sb19 = request.security('CRYPTO:EGLDUSD', timeframe.period, showFunc())
sb20 = request.security('MEXC:PENDLEUSDT', timeframe.period, showFunc())
sb21 = request.security('GATEIO:YGGUSDT', timeframe.period, showFunc())
sb22 = request.security('BINANCE:APEUSDT', timeframe.period, showFunc())
sb23 = request.security('BINANCE:CYBERUSDT', timeframe.period, showFunc())
sb24 = request.security('BINANCE:REEFUSDT', timeframe.period, showFunc())
sb25 = request.security('MEXC:HFTUSDT', timeframe.period, showFunc())
sb26 = request.security('MEXC:BAKEUSDT', timeframe.period, showFunc())
sb27 = request.security('CRYPTO:LOOMUSD', timeframe.period, showFunc())
sb28 = request.security('GATEIO:MOVRUSDT', timeframe.period, showFunc())
sb29 = request.security('CRYPTO:STORJUSD', timeframe.period, showFunc())
sb30 = request.security('MEXC:HIFIUSDT', timeframe.period, showFunc())
sb31 = request.security('GATEIO:IOTXUSDT', timeframe.period, showFunc())
sb32 = request.security('MEXC:KSMUSDT', timeframe.period, showFunc())
sb33 = request.security('GATEIO:FILUSDT', timeframe.period, showFunc())
sb34 = request.security('BINANCE:WLDUSDT', timeframe.period, showFunc())
sb35 = request.security('CRYPTO:GMTUSD', timeframe.period, showFunc())
sb36 = request.security('MEXC:IMXUSDT', timeframe.period, showFunc())
sb37 = request.security('BINANCE:STXUSDT', timeframe.period, showFunc())
sb38 = request.security('BINANCE:FLMUSDT', timeframe.period, showFunc())
sb39 = request.security('MEXC:JASMYUSDT', timeframe.period, showFunc())
sb40 = request.security('MEXC:ACHUSDT', timeframe.period, showFunc())

// Sadece son barı kontrol et ve tabloya ekle
if barstate.islast
    if sb1
        array.push(signalArr, 'BINANCE:BTCUSDT')
    if sb2
        array.push(signalArr, 'BINANCE:SOLUSDT')
    if sb3
        array.push(signalArr, 'BINANCE:AVAXUSDT')
    if sb4
        array.push(signalArr, 'BINANCE:ETCUSDT')
    if sb5
        array.push(signalArr, 'BINANCE:MAVUSDT')
    if sb6
        array.push(signalArr, 'BINANCE:RVNUSDT')
    if sb7
        array.push(signalArr, 'BINANCE:HOOKUSDT')
    if sb8
        array.push(signalArr, 'BINANCE:DYDXUSDT')
    if sb9
        array.push(signalArr, 'BINANCE:NTRNUSDT')
    if sb10
        array.push(signalArr, 'MEXC:GTCUSDT')
    if sb11
        array.push(signalArr, 'MEXC:RDNTUSDT')
    if sb12
        array.push(signalArr, 'OKX:DGBUSDT')
    if sb13
        array.push(signalArr, 'CRYPTO:CELOUSD')
    if sb14
        array.push(signalArr, 'CRYPTO:PEPEUSD')
    if sb15
        array.push(signalArr, 'GATEIO:MDTUSDT')
    if sb16
        array.push(signalArr, 'MEXC:BLURUSDT')
    if sb17
        array.push(signalArr, 'GATEIO:FLOKIUSDT')
    if sb18
        array.push(signalArr, 'GATEIO:ENSUSDT')
    if sb19
        array.push(signalArr, 'CRYPTO:EGLDUSD')
    if sb20
        array.push(signalArr, 'MEXC:PENDLEUSDT')
    if sb21
        array.push(signalArr, 'GATEIO:YGGUSDT')
    if sb22
        array.push(signalArr, 'BINANCE:APEUSDT')
    if sb23
        array.push(signalArr, 'BINANCE:CYBERUSDT')
    if sb24
        array.push(signalArr, 'BINANCE:REEFUSDT')
    if sb25
        array.push(signalArr, 'MEXC:HFTUSDT')
    if sb26
        array.push(signalArr, 'MEXC:BAKEUSDT')
    if sb27
        array.push(signalArr, 'CRYPTO:LOOMUSD')
    if sb28
        array.push(signalArr, 'GATEIO:MOVRUSDT')
    if sb29
        array.push(signalArr, 'CRYPTO:STORJUSD')
    if sb30
        array.push(signalArr, 'MEXC:HIFIUSDT')
    if sb31
        array.push(signalArr, 'GATEIO:IOTXUSDT')
    if sb32
        array.push(signalArr, 'MEXC:KSMUSDT')
    if sb33
        array.push(signalArr, 'GATEIO:FILUSDT')
    if sb34
        array.push(signalArr, 'BINANCE:WLDUSDT')
    if sb35
        array.push(signalArr, 'CRYPTO:GMTUSD')
    if sb36
        array.push(signalArr, 'MEXC:IMXUSDT')
    if sb37
        array.push(signalArr, 'BINANCE:STXUSDT')
    if sb38
        array.push(signalArr, 'BINANCE:FLMUSDT')
    if sb39
        array.push(signalArr, 'MEXC:JASMYUSDT')
    if sb40
        array.push(signalArr, 'MEXC:ACHUSDT')    

// Eğer çok fazla sinyal varsa, sadece bir kısmını ekle
maxRows = 50
rowCount = math.min(array.size(signalArr), maxRows)

if rowCount > 0 and barstate.islast
    var sigTable = table.new(position.top_right, columns=1, rows=rowCount)
    table.set_border_width(sigTable, 1)
    table.set_frame_width(sigTable, 1)
    table.set_border_color(sigTable, tableColor)
    table.set_frame_color(sigTable, tableColor)
   
    for i = 0 to rowCount - 1
        table.cell(sigTable, 0, i, text=array.get(signalArr, i), text_color=tableTextHeaderColor, bgcolor=tableBGColor)
        table.cell_set_height(sigTable, 0, i, 100 / rowCount)
        table.cell_set_text_size(sigTable, 0, i, size.auto)
